[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
extend-select = ['E', 'F', 'I', 'N', 'W', 'UP', 'RUF']
extend-ignore = ["F403", "F405"]